# Generated by Django 2.2.4 on 2019-08-02 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expenseName', models.TextField()),
                ('expenseAmt', models.DecimalField(decimal_places=2, max_digits=5)),
                ('expenseCategory', models.CharField(choices=[('UT', 'Utilities'), ('HC', 'Health Care'), ('OT', 'Other'), ('FD', 'Food/Grocery/Restaurant'), ('PC', 'Personal Care'), ('EN', 'Entertainment'), ('MF', 'Membership Fees'), ('PD', 'Personal Debt/Loans')], max_length=2)),
                ('expenseDate', models.DateField(auto_now=True)),
            ],
        ),
    ]
