# Generated by Django 2.2.4 on 2019-08-03 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_expensestat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenseitem',
            name='expenseAmt',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='expensestat',
            name='totalBudget',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='expensestat',
            name='totalExpense',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='expensestat',
            name='totalLeft',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
